---
- hosts: all
  gather_facts: true
  ignore_errors: true
  tasks:
    - name: Run VLAN resource module with state deleted
      alcatel.aos8.aos8_vlans:
        config:
          - vlan_id: 33
          - vlan_id: 99
        state: deleted
