# -*- coding: utf-8 -*-
# Copyright 2023 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function

__metaclass__ = type

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the
# cli_rm_builder.
#
# Manually editing this file is not advised.
#
# To update the argspec make the desired changes
# in the module docstring and re-run
# cli_rm_builder.
#
#############################################

"""
The arg spec for the aos8_command module
"""


class CommandArgs(object):  # pylint: disable=R0903
    """The arg spec for the aos8_command module
    """

    argument_spec = {
        "commands": {"required": True, "type": "list", "elements": "raw"},
        "wait_for": {"aliases": ["waitfor"], "type": "list", "elements": "str"},
        "match": {"default": "all", "type": "str", "choices": ["any", "all"]},
        "retries": {"default": 9, "type": "int"},
        "interval": {"default": 1, "type": "int"},
    }  # pylint: disable=C0301
